ALTER TABLE rooms
  ADD COLUMN is_eliminated BOOLEAN NOT NULL DEFAULT FALSE,
  ADD COLUMN votes INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN coins INTEGER NOT NULL DEFAULT 20,
  ADD COLUMN voted_for INTEGER;
